# Generated by Django 4.2.2 on 2023-06-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_alter_feed_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feed',
            name='image',
            field=models.ImageField(upload_to='downloads/'),
        ),
    ]
